# Generated by Django 3.2.5 on 2021-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_baseuser_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
